#!/bin/bash
# Takes as input a list of pids. Mutes (1) or unmutes (0) these processes depending on the argument $1
# Requires pulseaudio

index=-1
while read line; do
  pidlist+=" $line"
done
type=index

#this sed should return an index on every even line and a pid on every odd one
pacmd list-sink-inputs | sed -nr -e 's/^\s*index: (.*)/\1/p' -e 's/^\s*application\.process\.id = "(.*)"/\1/p' | while read line; do
  if [ "$type" == "index" ]; then
    index=$line
    type=pid
  else
    type=index
    for pidInList in $pidlist; do
      if [ "$line" == "$pidInList" ]; then
        pacmd set-sink-input-mute $index $1 > /dev/null
        break
      fi
    done
  fi
done
